
#' Generate a list of acoustic variables in list of EV files and
#' save that list in a csv file in the folder containing the 
#' EV files.
#' 
#' This function generates a list of all variables present in each
#' EV file in the list of EV files generated by the directory choice. 
#' 
#' @param ev.dir 
#' Character, the directory containing the EV files
#' @param EVFile 
#' Character, the name of the EV file being processed. Determine by
#' funciton.
#' @return
#' A csv file with variables "var", the name of each variable, "EV.name", the
#' full path/name for each EV file, "Nvar", the number of variables in the EV file,
#' and "EVfolder.name", the name of the subfolder containing the EV file.

#'
#' @keywords Echoview COM scripting
#' @author Dave Warner
#' 
#' @importFrom plyr rbind.fill
#' @export
#' 
get_acoVarNames_in_EVfiles <- function (ev.dir, EVFile) {
  ev.dir <- choose.dir()
  all.evfiles <- list.files(ev.dir, pattern="EV|ev", full.names = TRUE)
  scrap.files <- grep("evwx|evb|csv|evi|CAL|evw|backup", all.evfiles, value=TRUE)
  evfiles <- setdiff(all.evfiles, scrap.files)
  varname.df <- data.frame()
  all.ev <- data.frame()
  for (j in 1:length(evfiles)){
    try(
    EVAppObj <- COMCreate('EchoviewCom.EvApplication')
    )
    Sys.sleep(1)
    try(
    EVFile <- EVOpenFile(EVAppObj, evfiles[j])$EVFile
    )
    Sys.sleep(1)
    try(
    varlist <- EVFile[['Variables']]$Count()
    )
    Sys.sleep(1)
    Item <- seq(1, varlist, 1)
    try(
    for (i in 1:(varlist-1)){
      the.variables <- EVFile[['Variables']]
      var.name <- the.variables$Item(i)$Name()
      df <- data.frame(var = var.name, EV.name = NA, Nvar = NA, EVfolder.name = NA)
      varname.df <- rbind(varname.df, df)
      varname.df$Nvar <- varlist-1
      
    })
    Sys.sleep(1)
    try(
    varname.df$EV.name <- evfiles[j]
    )
    try(
    varname.df$EVfolder.name <- strsplit(strsplit(evfiles[j], "[\\]")[[1]][6],"[/]")[[1]][1]
    )
    try(
    all.ev<- rbind.fill(all.ev, varname.df)
    )
   try(EVAppObj$CloseFile(EVFile))
   Sys.sleep(1)
   out.dir <- strsplit(evfiles[j], "[/]")
   write.csv(all.ev, paste0(out.dir[[1]][[1]], Sys.Date(), "_varnames.csv"), row.names = FALSE)
  }
  EVAppObj$Quit()
}






